'use strict';
const $=s=>document.querySelector(s);const canvas=$('#board'),ctx=canvas.getContext('2d');
const W=900,C={cx:450,cy:450,R:365,pocket:31,baseline:315};let mode='ai',turn=0,players=[],coins=[],queen=null,drag=null,anim=0,last=0,gameOver=false,timer=20,timerId=null,sound=true,stats=JSON.parse(localStorage.getItem('carromStats')||'{"wins":0,"games":0}');
const COLORS=['#f3e5c7','#22252b','#f3e5c7','#22252b'];
function initPlayers(){players=mode==='4p'?[{name:'Player 1',score:0,fouls:0},{name:'Player 2',score:0,fouls:0},{name:'Player 3',score:0,fouls:0},{name:'Player 4',score:0,fouls:0}]:[{name:'Player 1',score:0,fouls:0},{name:mode==='ai'?'Computer':'Player 2',score:0,fouls:0}];}
function setup(){coins=[];const spacing=27;let idx=0;coins.push({x:C.cx,y:C.cy,r:12,color:'#c33b3b',type:'queen',vx:0,vy:0});for(let ring=1;ring<=2;ring++)for(let i=0;i<ring*6;i++){let a=i*Math.PI*2/(ring*6)+(ring%2?.12:0);coins.push({x:C.cx+Math.cos(a)*spacing*ring,y:C.cy+Math.sin(a)*spacing*ring,r:11,color:COLORS[idx++%2],type:'coin',vx:0,vy:0});}for(let i=0;i<2;i++)coins.push({x:C.cx+(i?160:-160),y:C.cy,r:13,color:'#dfbd73',type:'coin',vx:0,vy:0});queen=null;gameOver=false;turn=0;setTimer();feed('Match started. Player 1 to break.');draw();}
function start(m){mode=m;initPlayers();$('#home').classList.remove('active');$('#game').classList.add('active');$('#p1Name').textContent=players[0].name;$('#p2Name').textContent=players[1].name;setup();}
function reset(){clearInterval(timerId);setup();}
function feed(t){const e=document.createElement('div');e.textContent='› '+t;$('#feed').prepend(e);while($('#feed').children.length>8)$('#feed').lastChild.remove();}
function setTimer(){clearInterval(timerId);timer=20;$('#timer').textContent=timer;$('#timerBar').style.width='100%';timerId=setInterval(()=>{if(gameOver)return;timer--;$('#timer').textContent=timer;$('#timerBar').style.width=(timer/20*100)+'%';if(timer<=0){players[turn].fouls++;feed(players[turn].name+' timed out.');nextTurn();}},1000);}
function nextTurn(){turn=(turn+1)%players.length;$('#turnName').textContent=players[turn].name;$('#status').textContent=mode==='ai'&&turn===1?'Computer is thinking…':'Aim and shoot';updateMeta();setTimer();if(mode==='ai'&&turn===1)setTimeout(aiShot,650);}
function updateMeta(){players.forEach((p,i)=>{const el=i===0?$('#p1Meta'):$('#p2Meta');if(el)el.textContent=`${p.score} coins • ${p.fouls} fouls`;});$('#p1Score').textContent=players[0].score;$('#p2Score').textContent=players[1].score;}
function pocketFor(x,y){return [[35,35],[865,35],[35,865],[865,865]].some(p=>Math.hypot(x-p[0],y-p[1])<C.pocket);}
function physics(dt){for(const o of coins){if(Math.abs(o.vx)+Math.abs(o.vy)<.02)continue;o.x+=o.vx*dt;o.y+=o.vy*dt;o.vx*=Math.pow(.992,dt*60);o.vy*=Math.pow(.992,dt*60);if(pocketFor(o.x,o.y)){o.pocketed=true;o.vx=o.vy=0;players[turn].score+=o.type==='queen'?3:1;feed(`${players[turn].name} pocketed ${o.type==='queen'?'the Queen':'a coin'}!`);continue;}const dx=o.x-C.cx,dy=o.y-C.cy,d=Math.hypot(dx,dy);if(d>C.R-o.r){const nx=dx/d,ny=dy/d;const dot=o.vx*nx+o.vy*ny;o.vx-=2*dot*nx;o.vy-=2*dot*ny;o.x=C.cx+nx*(C.R-o.r);o.y=C.cy+ny*(C.R-o.r)}}for(let i=0;i<coins.length;i++)for(let j=i+1;j<coins.length;j++){let a=coins[i],b=coins[j];if(a.pocketed||b.pocketed)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d&&d<min){let nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;let rv=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rv>0){a.vx-=rv*nx;a.vy-=rv*ny;b.vx+=rv*nx;b.vy+=rv*ny}}}if(coins.filter(o=>!o.pocketed).every(o=>Math.abs(o.vx)+Math.abs(o.vy)<.02)&&anim){coins=coins.filter(o=>o.type!=='striker');anim=0;checkWin();}}
function checkWin(){const remaining=coins.filter(o=>!o.pocketed&&o.type==='coin').length;if(remaining===0){gameOver=true;clearInterval(timerId);stats.games++;if(turn===0)stats.wins++;localStorage.setItem('carromStats',JSON.stringify(stats));showEnd();}else nextTurn();}
function showEnd(){modal(`<div class="game-over"><div class="big">🏆</div><h2>${players[turn].name} WINS!</h2><p>All playable coins are cleared. Final score: <b>${players[turn].score}</b></p><p>Career wins: ${stats.wins}</p><button id="again" class="mode">PLAY AGAIN</button></div>`);$('#again').onclick=()=>{closeModal();reset();}}
function draw(){ctx.clearRect(0,0,W,W);ctx.fillStyle='#151a22';ctx.fillRect(0,0,W,W);ctx.save();ctx.translate(C.cx,C.cy);ctx.fillStyle='#b8894f';ctx.shadowColor='#0008';ctx.shadowBlur=30;ctx.beginPath();ctx.arc(0,0,395,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#f0d7a5';ctx.beginPath();ctx.arc(0,0,C.R+15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6f4b2a';ctx.lineWidth=9;ctx.beginPath();ctx.arc(0,0,C.R,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#a06b36';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,95,0,Math.PI*2);ctx.stroke();ctx.restore();for(const [x,y] of [[35,35],[865,35],[35,865],[865,865]]){ctx.fillStyle='#211c19';ctx.beginPath();ctx.arc(x,y,C.pocket,0,Math.PI*2);ctx.fill();ctx.fillStyle='#070707';ctx.beginPath();ctx.arc(x,y,C.pocket-8,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#9b6939';ctx.lineWidth=3;for(const y of [315,585]){ctx.beginPath();ctx.moveTo(120,y);ctx.lineTo(780,y);ctx.stroke();}for(const x of [315,585]){ctx.beginPath();ctx.moveTo(x,120);ctx.lineTo(x,780);ctx.stroke();}for(const o of coins)if(!o.pocketed){ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=7;ctx.fillStyle=o.color;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=o.type==='queen'?'#f5e0a0':'#8a7b62';ctx.lineWidth=2;ctx.stroke();ctx.restore();}drawStriker();}
function drawStriker(){const sx=turn%2?C.cx-160:C.cx+160;ctx.save();ctx.fillStyle='#d5ad63';ctx.shadowColor='#0009';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(sx,C.cy+220,17,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#6d4c2d';ctx.stroke();if(drag){ctx.strokeStyle='#fff8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(sx,C.cy+220);ctx.lineTo(drag.x,drag.y);ctx.stroke();}ctx.restore();}
function pointer(e){const r=canvas.getBoundingClientRect(),sx=e.clientX??e.touches?.[0].clientX,sy=e.clientY??e.touches?.[0].clientY;return{x:Math.max(0,Math.min(W,(sx-r.left)*W/r.width)),y:Math.max(0,Math.min(W,(sy-r.top)*W/r.height))}}
canvas.addEventListener('pointerdown',e=>{if(gameOver||mode==='ai'&&turn===1)return;const p=pointer(e),sx=turn%2?C.cx-160:C.cx+160,sy=C.cy+220;if(Math.hypot(p.x-sx,p.y-sy)<35){drag=p;canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!drag)return;drag=pointer(e);const sx=turn%2?C.cx-160:C.cx+160,sy=C.cy+220;const power=Math.min(100,Math.hypot(drag.x-sx,drag.y-sy)/2);$('#powerFill').style.width=power+'%';draw();});canvas.addEventListener('pointerup',e=>{if(!drag)return;const p=pointer(e),sx=turn%2?C.cx-160:C.cx+160,sy=C.cy+220;let dx=sx-p.x,dy=sy-p.y,len=Math.hypot(dx,dy);if(len>15){const power=Math.min(22,len/8);coins.push({x:sx,y:sy,r:17,color:'#d5ad63',type:'striker',vx:dx/len*power,vy:dy/len*power});anim=1;feed(players[turn].name+' shot.');$('#powerFill').style.width='0%';requestAnimationFrame(loop);}drag=null;draw();});
function aiShot(){if(gameOver)return;const sx=C.cx-160,sy=C.cy+220;let targets=coins.filter(o=>!o.pocketed&&o.type!=='striker');if(!targets.length)return;targets.sort((a,b)=>Math.hypot(a.x-35,a.y-35)-Math.hypot(b.x-35,b.y-35));let t=targets[Math.floor(Math.random()*Math.min(3,targets.length))];let dx=sx-t.x,dy=sy-t.y,len=Math.hypot(dx,dy);coins.push({x:sx,y:sy,r:17,color:'#d5ad63',type:'striker',vx:dx/len*10,vy:dy/len*10});anim=1;feed('Computer fired.');requestAnimationFrame(loop);}
function loop(ts){if(!last)last=ts;let dt=Math.min(2,(ts-last)/16.67);last=ts;physics(dt);draw();if(anim)requestAnimationFrame(loop);}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
$('#helpBtn').onclick=()=>modal('<h2>How to play</h2><ul><li>Drag from the striker and release to shoot.</li><li>Pocket black/white coins to score.</li><li>The Queen is worth 3 points.</li><li>A turn advances after all pieces stop.</li><li>Clear the board to win.</li><li>Timer: 20 seconds per turn.</li></ul><p>Tip: use short shots for control and bank shots for corners.</p>');$('#closeModal').onclick=closeModal;$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};$('#homeBtn').onclick=()=>{clearInterval(timerId);$('#game').classList.remove('active');$('#home').classList.add('active')};$('#newBtn').onclick=reset;document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));window.addEventListener('resize',draw);draw();
